### ISSUE TITLE
⌘-k not clearing the terminal

### ISSUE THREAD

**Issue by metasean** [microsoft/vscode-atom-keybindings#38]
**Versions**

_VS Code_: Version 1.15.1 (1.15.1) | 41abd21afdf7424c89319ee7cb0445cc6f376959 | 2017-08-16T17:11:22.564Z

_macOS Sierra_: Version 10.12.3

_Atom Keymap_ version: 3.0.1

---

**Problem**

⌘-k does not clear the terminal as expected

**Steps to Reproduce**

1. Install and activate "Atom Keymap" ("Code" > "Preferences" > "Keymap Extensions (⌘-K ⌘-M)")
2. Open integrated terminal and ensure it has focus (`⌘-
![firefox-nightly-57-about-logo](https://user-images.githubusercontent.com/7552754/29482008-11f040c8-8446-11e7-9c97-ad216c3ede8f.png)
`)
3. Press `⌘-k` to trigger the clear command

![image](https://user-images.githubusercontent.com/7552754/29481954-4602e2d6-8445-11e7-9fa9-827dd4091fa8.png)

**Expected**
Clears terminal

**Actual**
Shows message about chord and does not execute clear:

![image](https://user-images.githubusercontent.com/7552754/29481951-3d8dc6f2-8445-11e7-93dc-213ac6c1baac.png)

**Notes**
- (a) Disabling the Atom Keymap, (b) removing the `"atomKeymap.promptV3Features": true,` from my settings, and (c) restarting VS Code fixes the problem, _but of course, doing so leaves me without the Atom Keymapping_. :-(
- related discussion (such that it was): https://github.com/Microsoft/vscode/issues/25059

**Comment by egamma** [comment]
@chrisdias @auchenberg @seanmcbreen assigning to all of you, the extension was maintained by @waderyan in the past.

**Comment by auchenberg** [comment]
This does indeed reproduce with keymap + default settings. If `cmd+k` is set as a user setting it works. I assume some default keybindings are being overridden as the keymap defines `cmd+k +` keys.

**Comment by gottfrois** [comment]
any news regarding this issue?

**Comment by am17torres** [comment]
For those of you who are okay with hacks. This is how I resolved the issue.

![](https://files.slack.com/files-pri/T5UEXVCNT-FAEESHUAF/screen_shot_2018-04-27_at_9.58.06_am.png)

**Comment by bartocc** [comment]
I'll go with @am17torres HACK while this issue is not resolved

**Comment by bretonics** [comment]
I just started trying VSCode (coming from Atom) and experienced the same issue of Terminal not clearing. Any updates on this?

**Comment by chrisdias** [comment]
fixed
