### ISSUE TITLE
When renaming file, the 'h' key causes the rename input to lose focus

### ISSUE THREAD

**Issue by neenjaw** [Microsoft/vscode-atom-keybindings#44]
Like the title says, when I have the keybinding loaded to the workspace, I can't press the 'h' key without it losing focus, and even sometimes making a new file with the partial file name.  When I disable the key binding and reload the workspace, it is fixed and I can rename as expected.  I have attached a gif to describe this behavior.

[gif](https://i.gyazo.com/b936e033d2d90f699b4a02e790dd8687.gif)

**Comment by rwatts3** [comment]
This is actually a major problem, i've nearly destroyed a project due to this issue by accidentally renaming a file, and creating a mute file, since it grabs focus and starts creating a new file on each keystroke after h.

**Comment by auchenberg** [comment]
Hi @neenjaw, @rwatts3 

Indeed this is a bug. We are working on a fix for Code, but I've updated the keymap with a fix, so please update this keymap, and things hopefully should work.

/k

**Comment by auchenberg** [comment]
Release fixed in v3.0.3

**Comment by neenjaw** [comment]
Awesome, did not know there was an inputFocus flag. Will try it out
