### ISSUE TITLE
How to change the current platform?

### ISSUE THREAD

**Issue by xdmx** [Microsoft/vscode-atom-keybindings#48]
I'm using VS Code with the atom keybindings on OSX, but I'm used to have it under linux. Is it possible to change the platform that VS Code uses (from the OSX to linux) and use the respective keybinding?

**Comment by auchenberg** [comment]
@xdmx Not sure I understand. On your Linux machine you can install this atom key map too and your MacOS machine you can install it too?

**Comment by xdmx** [comment]
Hi Kenneth, I mean if I can have the same atom key bindings on both OS (based on the Linux one), so having for example `ctrl+c` to copy on both systems instead of having `command+c` on MacOS and `ctrl+x` on Linux, without having to manually remap all of them

**Comment by auchenberg** [comment]
Ah @xdmx at this point in time we don't support this. The intent of the keymaps is to mimimic the original keyboard shortcuts for Atom, so you would have to copy paste them manually into your own keybindings.json file.  You can simply copy them from https://github.com/Microsoft/vscode-atom-keybindings/blob/master/package.json#L24, and remove the `mac`, `win`, `linux` keys, but keeping `key` around.
