### ISSUE TITLE
Windows: bunch of warnings in console

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-atom-keybindings#5]
Refs: Microsoft/vscode#14318

Install the extension
F1 > developer tools

Notice many warnings. Some of these are because you are overwriting default keybindings but some should not be used on windows. Not sure if you can do something about it though

![screen shot 2016-10-25 at 12 01 38](https://cloud.githubusercontent.com/assets/1926584/19681727/e553945a-9aaa-11e6-92af-00926e8185dd.png)

**Comment by waderyan** [comment]
@alexandrudima do you know why I would be seeing this and how I can fix it? Could use your expertise.

**Comment by waderyan** [comment]
Note that this is also seen on Mac. 

![image](https://cloud.githubusercontent.com/assets/2449568/19701771/b2444e04-9ab1-11e6-86c7-a6df20fceef8.png)

**Comment by isidorn** [comment]
@waderyan well you are seeing it because you overriding all those default keybindings and now those actions can not be invoked. AFAIK we do not have support to supress these warnings since they are useful in the end - the user is informed what keybindings are overtaken

**Comment by alexandrudima** [comment]
@waderyan I did not consider the keymap extension scenario when I've added those warnings. I can remove all of them, but then the risk will grow that we make mistakes in the default ones we ship with...

**Comment by waderyan** [comment]
@alexandrudima let's think about it a bit more... I'm thinking that there are too many users opening the developer console that will be concerned with the warnings.

**Comment by waderyan** [comment]
@alexandrudima let's think about it a bit more... I'm thinking that there are too many users opening the developer console that will be concerned with the warnings.

**Comment by chrisdias** [comment]
does not happen on macOS

**Comment by chrisdias** [comment]
i don't see this, closing.
