### ISSUE TITLE
"promptV3Features" set to `false` fails

### ISSUE THREAD

**Issue by mjstelly** [microsoft/vscode-atom-keybindings#61]
Whenever I launch VSC, I receive the "use new features" prompt. I select YES. If I close and relaunch VSC, I receive the same prompt. In both my user and workspace settings json, I set `"atomKeymap.promptV3Features": false`. I still get prompted.

Using VSC Version 1.35.1 (1.35.1)

How do I prevent the new feature prompt from reappearing?

**Comment by chrisdias** [comment]
i can't repro this. if it is still a problem, please let me know.
